#pragma once
#include <uipc/geometry/utils/factory.h>
#include <uipc/geometry/utils/apply_transform.h>
#include <uipc/geometry/utils/closure.h>
#include <uipc/geometry/utils/label_surface.h>
#include <uipc/geometry/utils/label_triangle_orient.h>
#include <uipc/geometry/utils/flip_inward_triangles.h>
#include <uipc/geometry/utils/extract_surface.h>
#include <uipc/geometry/utils/merge.h>
#include <uipc/geometry/utils/simplex_utils.h>
#include <uipc/geometry/utils/label_connected_vertices.h>
#include <uipc/geometry/utils/label_region.h>
#include <uipc/geometry/utils/apply_region.h>
#include <uipc/geometry/utils/tetrahedralize.h>
#include <uipc/geometry/utils/compute_instance_volume.h>
#include <uipc/geometry/utils/optimal_transform.h>
